module VerifyExamples.Shared.Level.Next0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Level exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#next: \n\n    init\n        |> next\n        |> number\n    --> 2" <|
        \() ->
            Expect.equal
                (
                init
                    |> next
                    |> number
                )
                (
                2
                )