module VerifyExamples.Shared.Level.Number0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Level exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#number: \n\n    init\n        |> number\n    --> 1" <|
        \() ->
            Expect.equal
                (
                init
                    |> number
                )
                (
                1
                )