module VerifyExamples.Shared.Level.Previous1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Level exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#previous: \n\n    init\n        |> goto 5\n        |> previous\n        |> number\n    --> 4" <|
        \() ->
            Expect.equal
                (
                init
                    |> goto 5
                    |> previous
                    |> number
                )
                (
                4
                )