module VerifyExamples.Shared.Point.Move0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#move: \n\n    init\n        { x = 5\n        , y = 10\n        }\n        |> move\n            (init\n                { x = 10\n                , y = 20\n                }\n            )\n    --> init { x = 15, y = 30 }" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 5
                    , y = 10
                    }
                    |> move
                        (init
                            { x = 10
                            , y = 20
                            }
                        )
                )
                (
                init { x = 15, y = 30 }
                )