module VerifyExamples.Shared.Point.MoveToY0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#moveToY: \n\n    init\n        { x = 5\n        , y = 10\n        }\n        |> moveToY 5\n    --> init { x = 5, y = 5 }" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 5
                    , y = 10
                    }
                    |> moveToY 5
                )
                (
                init { x = 5, y = 5 }
                )