module VerifyExamples.Shared.Point.MoveRight0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#moveRight: \n\n    init\n        { x = 5\n        , y = 10\n        }\n        |> moveRight 5\n    --> init { x = 10, y = 10 }" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 5
                    , y = 10
                    }
                    |> moveRight 5
                )
                (
                init { x = 10, y = 10 }
                )