module VerifyExamples.Shared.Point.MoveLeft0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#moveLeft: \n\n    init\n        { x = 10\n        , y = 5\n        }\n        |> moveLeft 5\n    --> init { x = 5, y = 5 }" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 10
                    , y = 5
                    }
                    |> moveLeft 5
                )
                (
                init { x = 5, y = 5 }
                )