module VerifyExamples.Shared.Point.MoveToX0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#moveToX: \n\n    init\n        { x = 5\n        , y = 10\n        }\n        |> moveToX 15\n    --> init { x = 15, y = 10 }" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 5
                    , y = 10
                    }
                    |> moveToX 15
                )
                (
                init { x = 15, y = 10 }
                )