module VerifyExamples.Shared.Point.XToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#xToString: \n\n    init\n        { x = 5\n        , y = 10\n        }\n        |> xToString\n    --> \"5\"" <|
        \() ->
            Expect.equal
                (
                init
                    { x = 5
                    , y = 10
                    }
                    |> xToString
                )
                (
                "5"
                )