module VerifyExamples.Shared.Point.Zero0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Point exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#zero: \n\n    zero\n    --> init { x = 0, y = 0 }" <|
        \() ->
            Expect.equal
                (
                zero
                )
                (
                init { x = 0, y = 0 }
                )