module VerifyExamples.Shared.Players.GameOverForPlayer1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)
import Shared.Scores as Scores







spec1 : Test.Test
spec1 =
    Test.test "#gameOverForPlayer: \n\n    init\n        (Lives 3)\n        (Highscores\n            { list = []\n            , max = 5\n            }\n        )\n        |> register \"Paul\"\n        |> incrementScoreForPlayer 1 100\n        |> gameOverForPlayer 1\n        |> highscores\n        |> Scores.highest\n        |> Scores.points\n    --> 100" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores
                        { list = []
                        , max = 5
                        }
                    )
                    |> register "Paul"
                    |> incrementScoreForPlayer 1 100
                    |> gameOverForPlayer 1
                    |> highscores
                    |> Scores.highest
                    |> Scores.points
                )
                (
                100
                )