module VerifyExamples.Shared.Players.GameOverForCurrentPlayer2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)
import Shared.Scores as Scores







spec2 : Test.Test
spec2 =
    Test.test "#gameOverForCurrentPlayer: \n\n    init\n        (Lives 3)\n        (Highscores\n            { list = []\n            , max = 0\n            }\n        )\n        |> register \"Paul\"\n        |> gameOverForCurrentPlayer\n        |> livesForCurrentPlayer\n    --> 0" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores
                        { list = []
                        , max = 0
                        }
                    )
                    |> register "Paul"
                    |> gameOverForCurrentPlayer
                    |> livesForCurrentPlayer
                )
                (
                0
                )