module VerifyExamples.Shared.Players.Highscores0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)
import Shared.Scores as Scores







spec0 : Test.Test
spec0 =
    Test.test "#highscores: \n\n    init\n        (Lives 3)\n        (Highscores\n            { list = [{name = \"James\", points = 100}]\n            , max = 10\n            }\n        )\n        |> highscores\n        |> Scores.highest\n        |> Scores.points\n    --> 100" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores
                        { list = [{name = "James", points = 100}]
                        , max = 10
                        }
                    )
                    |> highscores
                    |> Scores.highest
                    |> Scores.points
                )
                (
                100
                )