module VerifyExamples.Shared.Players.PointsForPlayer2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#pointsForPlayer: \n\n    init\n        (Lives 3)\n        (Highscores\n            { list = []\n            , max = 10\n            }\n        )\n        |> register \"Paul\"\n        |> register \"Steve\"\n        |> incrementScoreForPlayer 1 10\n        |> pointsForPlayer 1\n    --> Just 10" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores
                        { list = []
                        , max = 10
                        }
                    )
                    |> register "Paul"
                    |> register "Steve"
                    |> incrementScoreForPlayer 1 10
                    |> pointsForPlayer 1
                )
                (
                Just 10
                )