module VerifyExamples.Shared.Players.ScoreForPlayer1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)
import Shared.Scores as Scores







spec1 : Test.Test
spec1 =
    Test.test "#scoreForPlayer: \n\n    init\n        (Lives 3)\n        (Highscores\n            { list = []\n            , max = 10\n            }\n        )\n        |> register \"Paul\"\n        |> register \"Steve\"\n        |> incrementScoreForPlayer 1 10\n        |> scoreForPlayer 1\n        |> Maybe.withDefault (Scores.register \"\")\n        |> Scores.points\n    --> 10" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores
                        { list = []
                        , max = 10
                        }
                    )
                    |> register "Paul"
                    |> register "Steve"
                    |> incrementScoreForPlayer 1 10
                    |> scoreForPlayer 1
                    |> Maybe.withDefault (Scores.register "")
                    |> Scores.points
                )
                (
                10
                )