module VerifyExamples.Shared.Players.StateForCurrentPlayer0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#stateForCurrentPlayer: \n\n    init\n        (Lives 3)\n        (Highscores { list = []\n        , max = 0\n        })\n        |> register \"Paul\"\n        |> stateForCurrentPlayer\n    --> NoState" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores { list = []
                    , max = 0
                    })
                    |> register "Paul"
                    |> stateForCurrentPlayer
                )
                (
                NoState
                )