module VerifyExamples.Shared.Players.State1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#state: \n\n    init\n        (Lives 3)\n        (Highscores { list = []\n        , max = 0\n        })\n        |> register \"Paul\"\n        |> current\n        |> storeState\n            { enemies = 5 }\n        |> state\n    --> State { enemies = 5 }" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores { list = []
                    , max = 0
                    })
                    |> register "Paul"
                    |> current
                    |> storeState
                        { enemies = 5 }
                    |> state
                )
                (
                State { enemies = 5 }
                )