module VerifyExamples.Shared.Players.StateForPlayer1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Players exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#stateForPlayer: \n\n    init\n        (Lives 3)\n        (Highscores { list = []\n        , max = 0\n        })\n        |> register \"Paul\"\n        |> stateForPlayer 1\n    --> Just NoState" <|
        \() ->
            Expect.equal
                (
                init
                    (Lives 3)
                    (Highscores { list = []
                    , max = 0
                    })
                    |> register "Paul"
                    |> stateForPlayer 1
                )
                (
                Just NoState
                )