module VerifyExamples.Shared.BoundingBox.Calculate0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#calculate: \n\n    calculate\n        [ { boundingBox =\n                init\n                    { left = 10\n                    , top = 10\n                    , right = 20\n                    , bottom = 20\n                    }\n          }\n        , { boundingBox =\n                init\n                    { left = 5\n                    , top = 5\n                    , right = 15\n                    , bottom = 15\n                    }\n          }\n        ]\n        { boundingBox = zero }\n    --> { boundingBox = init { left = 5, top = 5, right = 20, bottom = 20 } }" <|
        \() ->
            Expect.equal
                (
                calculate
                    [ { boundingBox =
                            init
                                { left = 10
                                , top = 10
                                , right = 20
                                , bottom = 20
                                }
                      }
                    , { boundingBox =
                            init
                                { left = 5
                                , top = 5
                                , right = 15
                                , bottom = 15
                                }
                      }
                    ]
                    { boundingBox = zero }
                )
                (
                { boundingBox = init { left = 5, top = 5, right = 20, bottom = 20 } }
                )