module VerifyExamples.Shared.BoundingBox.Center0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#center: \n\n    center\n        (init\n            { left = 10\n            , top = 10\n            , right = 20\n            , bottom = 20\n            }\n        )\n    --> Point.init { x = 15, y = 15 }" <|
        \() ->
            Expect.equal
                (
                center
                    (init
                        { left = 10
                        , top = 10
                        , right = 20
                        , bottom = 20
                        }
                    )
                )
                (
                Point.init { x = 15, y = 15 }
                )