module VerifyExamples.Shared.BoundingBox.DecrementRight0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#decrementRight: \n\n    decrementRight\n        15\n        (init\n            { left = 5\n            , top = 0\n            , right = 15\n            , bottom = 10\n            }\n        )\n    --> init { left = 5, top = 0, right = 5, bottom = 10 }" <|
        \() ->
            Expect.equal
                (
                decrementRight
                    15
                    (init
                        { left = 5
                        , top = 0
                        , right = 15
                        , bottom = 10
                        }
                    )
                )
                (
                init { left = 5, top = 0, right = 5, bottom = 10 }
                )