module VerifyExamples.Shared.BoundingBox.FromPoint0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#fromPoint: \n\n    fromPoint\n        (Point.init\n            { x = 5\n            , y = 10\n            }\n        )\n    --> init { left = 5, top = 10, right = 5, bottom = 10 }" <|
        \() ->
            Expect.equal
                (
                fromPoint
                    (Point.init
                        { x = 5
                        , y = 10
                        }
                    )
                )
                (
                init { left = 5, top = 10, right = 5, bottom = 10 }
                )