module VerifyExamples.Shared.BoundingBox.GrowAroundCenter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#growAroundCenter: \n\n    growAroundCenter\n        5\n        { boundingBox =\n            init\n                { left = 10\n                , top = 10\n                , right = 20\n                , bottom = 20\n                }\n        }\n    --> { boundingBox = init { left = 7.5, top = 7.5, right = 22.5, bottom = 22.5 }}" <|
        \() ->
            Expect.equal
                (
                growAroundCenter
                    5
                    { boundingBox =
                        init
                            { left = 10
                            , top = 10
                            , right = 20
                            , bottom = 20
                            }
                    }
                )
                (
                { boundingBox = init { left = 7.5, top = 7.5, right = 22.5, bottom = 22.5 }}
                )