module VerifyExamples.Shared.BoundingBox.Init0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#init: \n\n    init\n        { left = 5\n        , top = 30\n        , right = 10\n        , bottom = 20\n        }\n        |> bottom\n    --> 30" <|
        \() ->
            Expect.equal
                (
                init
                    { left = 5
                    , top = 30
                    , right = 10
                    , bottom = 20
                    }
                    |> bottom
                )
                (
                30
                )