module VerifyExamples.Shared.BoundingBox.Init1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#init: \n\n    init\n        { left = 5\n        , top = 10\n        , right = 0\n        , bottom = 20\n        }\n        |> right\n    --> 5" <|
        \() ->
            Expect.equal
                (
                init
                    { left = 5
                    , top = 10
                    , right = 0
                    , bottom = 20
                    }
                    |> right
                )
                (
                5
                )