module VerifyExamples.Shared.BoundingBox.MoveRight0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#moveRight: \n\n    moveRight\n        5\n        (init\n            { left = 10\n            , top = 10\n            , right = 20\n            , bottom = 20\n            }\n        )\n    --> init { left = 15, top = 10, right = 25, bottom = 20 }" <|
        \() ->
            Expect.equal
                (
                moveRight
                    5
                    (init
                        { left = 10
                        , top = 10
                        , right = 20
                        , bottom = 20
                        }
                    )
                )
                (
                init { left = 15, top = 10, right = 25, bottom = 20 }
                )