module VerifyExamples.Shared.BoundingBox.Move0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#move: \n\n    move\n        (Point.init\n            { x = 5\n            , y = 10\n            }\n        )\n        (init\n            { left = 10\n            , top = 10\n            , right = 20\n            , bottom = 20\n            }\n        )\n    --> init { left = 15, top = 20, right = 25, bottom = 30 }" <|
        \() ->
            Expect.equal
                (
                move
                    (Point.init
                        { x = 5
                        , y = 10
                        }
                    )
                    (init
                        { left = 10
                        , top = 10
                        , right = 20
                        , bottom = 20
                        }
                    )
                )
                (
                init { left = 15, top = 20, right = 25, bottom = 30 }
                )