module VerifyExamples.Shared.BoundingBox.MoveTo0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#moveTo: \n\n    moveTo\n        (Point.init\n            { x = 5\n            , y = 7.5\n            }\n        )\n        (init\n            { left = 10\n            , top = 10\n            , right = 20\n            , bottom = 20\n            }\n        )\n    --> init { left = 5, top = 7.5, right = 15, bottom = 17.5 }" <|
        \() ->
            Expect.equal
                (
                moveTo
                    (Point.init
                        { x = 5
                        , y = 7.5
                        }
                    )
                    (init
                        { left = 10
                        , top = 10
                        , right = 20
                        , bottom = 20
                        }
                    )
                )
                (
                init { left = 5, top = 7.5, right = 15, bottom = 17.5 }
                )