module VerifyExamples.Shared.BoundingBox.ShrinkAroundCenter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#shrinkAroundCenter: \n\n    shrinkAroundCenter\n        12\n        { boundingBox =\n            init\n                { left = 0\n                , top = 0\n                , right = 10\n                , bottom = 10\n                }\n        }\n    --> { boundingBox = init { left = 5, top = 5, right = 5, bottom = 5 }}" <|
        \() ->
            Expect.equal
                (
                shrinkAroundCenter
                    12
                    { boundingBox =
                        init
                            { left = 0
                            , top = 0
                            , right = 10
                            , bottom = 10
                            }
                    }
                )
                (
                { boundingBox = init { left = 5, top = 5, right = 5, bottom = 5 }}
                )