module VerifyExamples.Shared.BoundingBox.ShrinkAroundCenter1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#shrinkAroundCenter: \n\n    shrinkAroundCenter\n        4\n        { boundingBox =\n            init\n                { left = 0\n                , top = 0\n                , right = 10\n                , bottom = 10\n                }\n        }\n    --> { boundingBox = init { left = 2, top = 2, right = 8, bottom = 8 }}" <|
        \() ->
            Expect.equal
                (
                shrinkAroundCenter
                    4
                    { boundingBox =
                        init
                            { left = 0
                            , top = 0
                            , right = 10
                            , bottom = 10
                            }
                    }
                )
                (
                { boundingBox = init { left = 2, top = 2, right = 8, bottom = 8 }}
                )