module VerifyExamples.Shared.BoundingBox.ToPoint0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#toPoint: \n\n    toPoint\n        (init\n            { left = 5\n            , top = 10\n            , right = 15\n            , bottom = 20\n            }\n        )\n    --> Point.init { x = 5, y = 10 }" <|
        \() ->
            Expect.equal
                (
                toPoint
                    (init
                        { left = 5
                        , top = 10
                        , right = 15
                        , bottom = 20
                        }
                    )
                )
                (
                Point.init { x = 5, y = 10 }
                )