module VerifyExamples.Shared.BoundingBox.TopToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#topToString: \n\n    topToString\n        (init\n            { left = 5\n            , top = 10\n            , right = 15\n            , bottom = 20\n            }\n        )\n    --> \"10\"" <|
        \() ->
            Expect.equal
                (
                topToString
                    (init
                        { left = 5
                        , top = 10
                        , right = 15
                        , bottom = 20
                        }
                    )
                )
                (
                "10"
                )