module VerifyExamples.Shared.BoundingBox.Width0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#width: \n\n    width\n        (init\n            { left = 5, top = 10, right = 17, bottom = 20 }\n        )\n    --> 12" <|
        \() ->
            Expect.equal
                (
                width
                    (init
                        { left = 5, top = 10, right = 17, bottom = 20 }
                    )
                )
                (
                12
                )