module VerifyExamples.Shared.BoundingBox.Zero0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.BoundingBox exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#zero: \n\n    zero\n    --> init { left = 0, top = 0, right = 0, bottom = 0 }" <|
        \() ->
            Expect.equal
                (
                zero
                )
                (
                init { left = 0, top = 0, right = 0, bottom = 0 }
                )