module VerifyExamples.Shared.Movement.MovePoint0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Movement exposing (..)
import Shared.Point as Point







spec0 : Test.Test
spec0 =
    Test.test "#movePoint: \n\n    Point.zero\n    |> movePoint (Right 10)\n    |> movePoint (Down 5)\n    --> Point.init { x = 10, y = 5 }" <|
        \() ->
            Expect.equal
                (
                Point.zero
                |> movePoint (Right 10)
                |> movePoint (Down 5)
                )
                (
                Point.init { x = 10, y = 5 }
                )