module VerifyExamples.Shared.Scores.DecrementScore0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#decrementScore: \n\n    register \"Paul\"\n        |> incrementScore 10\n        |> decrementScore 3\n        |> points\n    --> 7" <|
        \() ->
            Expect.equal
                (
                register "Paul"
                    |> incrementScore 10
                    |> decrementScore 3
                    |> points
                )
                (
                7
                )