module VerifyExamples.Shared.Scores.IncrementScore0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#incrementScore: \n\n    register \"Paul\"\n        |> incrementScore 10\n        |> incrementScore 5\n        |> points\n    --> 15" <|
        \() ->
            Expect.equal
                (
                register "Paul"
                    |> incrementScore 10
                    |> incrementScore 5
                    |> points
                )
                (
                15
                )