module VerifyExamples.Shared.Scores.Init2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#init: \n\n    init\n        10\n        [ { name = \"Paul\"\n          , points = 1000\n          }\n        , { name = \"Steve\"\n          , points = 900\n          }\n        ]\n        |> list\n        |> List.length\n    --> 10" <|
        \() ->
            Expect.equal
                (
                init
                    10
                    [ { name = "Paul"
                      , points = 1000
                      }
                    , { name = "Steve"
                      , points = 900
                      }
                    ]
                    |> list
                    |> List.length
                )
                (
                10
                )