module VerifyExamples.Shared.Scores.Init1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#init: \n\n    init\n        2\n        [ { name = \"Paul\"\n          , points = 1000\n          }\n        , { name = \"Steve\"\n          , points = 900\n          }\n        , { name = \"Jeremy\"\n          , points = 800\n          }\n        ]\n        |> list\n        |> List.length\n    --> 2" <|
        \() ->
            Expect.equal
                (
                init
                    2
                    [ { name = "Paul"
                      , points = 1000
                      }
                    , { name = "Steve"
                      , points = 900
                      }
                    , { name = "Jeremy"
                      , points = 800
                      }
                    ]
                    |> list
                    |> List.length
                )
                (
                2
                )