module VerifyExamples.Shared.Scores.Lowest0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#lowest: \n\n    init\n        2\n        [ { name = \"Paul\"\n          , points = 1000\n          }\n        , { name = \"Steve\"\n          , points = 900\n          }\n        ]\n        |> lowest\n        |> points\n    --> 900" <|
        \() ->
            Expect.equal
                (
                init
                    2
                    [ { name = "Paul"
                      , points = 1000
                      }
                    , { name = "Steve"
                      , points = 900
                      }
                    ]
                    |> lowest
                    |> points
                )
                (
                900
                )