module VerifyExamples.Shared.Scores.PrepareForSave0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#prepareForSave: \n\n    init\n        3\n        [ { name = \"Paul\"\n          , points = 1000\n          }\n        , { name = \"Steve\"\n          , points = 900\n          }\n        ]\n        |> prepareForSave\n    --> [ {name = \"Paul\", points = 1000}, {name = \"Steve\", points = 900}, {name = \"---\", points = 0}]" <|
        \() ->
            Expect.equal
                (
                init
                    3
                    [ { name = "Paul"
                      , points = 1000
                      }
                    , { name = "Steve"
                      , points = 900
                      }
                    ]
                    |> prepareForSave
                )
                (
                [ {name = "Paul", points = 1000}, {name = "Steve", points = 900}, {name = "---", points = 0}]
                )