module VerifyExamples.Shared.Scores.Register1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#register: \n\n    register \"Paul\"\n        |> name\n    --> \"Paul\"" <|
        \() ->
            Expect.equal
                (
                register "Paul"
                    |> name
                )
                (
                "Paul"
                )