module VerifyExamples.Shared.Scores.Register0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Shared.Scores exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#register: \n\n    register \"Paul\"\n        |> points\n    --> 0" <|
        \() ->
            Expect.equal
                (
                register "Paul"
                    |> points
                )
                (
                0
                )